import { Blog } from "../types/types";

export const blogs: Blog[] = [
    { title: "2023 Blog Refresh", views: 10434 },
    { title: "Why I'm Using Next.js", views: 81020 },
    { title: "Product and Platform Engineers", views: 18950 },
    { title: "Make Something Developers Want", views: 10646 },
    { title: "Community-Messaging Fit", views: 66268 },
    { title: "Funding Open Source", views: 24510 },
    { title: "2023 State of Databases for Serverless & Edge", views: 67518 },
    { title: "Why You Should Use a React Framework", views: 26564 },
    { title: "Why I'm Optimistic About JavaScript's Future", views: 23092 },
    { title: "Behind the scenes: Next.js Conf 2022", views: 4954 },
    { title: "What Makes a Great Developer Experience?", views: 34199 },
    { title: "The Story of Heroku", views: 39152 },
    { title: "What is Developer Relations?", views: 9104 },
    { title: "Building an Image Gallery with Next.js, Supabase, and Tailwind CSS", views: 27526 },
    { title: "Developer's Guide to Video Production: Fundamentals of Video", views: 4369 },
    { title: "Rust Is The Future of JavaScript Infrastructure", views: 296796 },
    { title: "From Firebase/Redis to MySQL with PlanetScale", views: 15424 },
    { title: "How I Became a Software Engineer (From Designer to Developer)", views: 7644 },
    { title: "Using Serverless Redis with Next.js", views: 18624 },
    { title: "Past, Present, and Future of React State Management", views: 156643 },
    { title: "Web Fonts in 2021", views: 19646 },
    { title: "How Should I Style My React Application?", views: 16539 },
    { title: "Using the Spotify API with Next.js", views: 19990 },
    { title: "Create a Dynamic Sitemap with Next.js", views: 57629 },
    { title: "Create A Newsletter with Next.js API Routes and Mailchimp", views: 20520 },
    { title: "Real-Time Blog Post Views With Next.js and Firebase", views: 17020 },
    { title: "Everything I Know About Style Guides, Design Systems, and Component Libraries", views: 189958 },
    { title: "Using Firebase with Next.js", views: 36879 },
    { title: "How To Print in React Using Iframes", views: 25021 },
    { title: "Building a Design System Monorepo with Turborepo", views: 92910 },
    { title: "Technical Recruiting is Broken", views: 16882 },
    { title: "Things I've Learned Building Next.js Apps", views: 33932 },
    { title: "How Stripe Designs Beautiful Websites", views: 95454 },
    { title: "Creating a Loading Placeholder with Sass", views: 17561 },
    { title: "Programming Portfolios", views: 12857 },
    { title: "Creating a Space Invaders Clone with Python", views: 21039 },
];